source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :osx, '10.13'
workspace 'eqMac.xcworkspace'
use_frameworks!



# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
  pod 'STPrivilegedTask', :git => 'https://github.com/sveinbjornt/STPrivilegedTask.git', :tag => '1.0.7'
end

project 'app/eqMac.xcodeproj'

target 'eqMac' do
  project 'app/eqMac.xcodeproj'

  pod 'SwiftHTTP', '~> 3.0'
  pod 'AMCoreAudio', :git => 'https://github.com/elzii/AMCoreAudio.git'
  pod 'WebViewJavascriptBridge', '~> 6.0'
#  pod 'ReachabilitySwift'
  pod 'ReSwift', '~> 6.1'
  pod 'SwiftLint'
  pod 'Sparkle', '~> 1.24'
  pod 'Sentry', '~> 8.0'
  pod 'EmitterKit', '~> 5.2.2'
  pod 'SwiftyJSON', '~> 4.2'
  pod 'SwiftyUserDefaults', '4.0'
  pod 'KeychainSwift', '~> 13.0'
  pod 'Zip', :git => 'https://github.com/bitgapp/Zip.git', :tag => '2.1.1'
  shared_pods

end


